### ISSUE TITLE
Compilation issue with fixtures

### ISSUE THREAD

**Issue by IonutCava** [cppocl/unit_test_framework#27]
Using TEST_SETUP with the latest changes causes various compilation issues. The source of the problem seems to be the TEST_SETUP_TEARDOWN macro definition in TestMacros.hpp, more precisely, in the non-copyable property setup:

TestSetupTeardownFunctor_##Type##_##class_name(TestSetupTeardownFunctor_##Type##_##class_name const&) :  \
TestSetupTeardownFunctor_##Type##_##class_name& operator= TestSetupTeardownFunctor_##Type##_##class_name const&) :  \

should be :

private: \
            TestSetupTeardownFunctor_##Type##_##class_name(TestSetupTeardownFunctor_##Type##_##class_name const&) ;  \
TestSetupTeardownFunctor_##Type##_##class_name& operator= TestSetupTeardownFunctor_##Type##_##class_name const&) ;  \

Note the ':' to';' chnage at the end of the lines.

**Comment by colinrg** [comment]
Thanks, I will have a look after lunch.



Sent from Samsung Mobile

-------- Original message --------

**Comment by colinrg** [comment]
Fixed.
